AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-opencv

  SAM Template for aws-sam-opencv

Globals:
  Function:
    Timeout: 3
  Api:
    BinaryMediaTypes:
      - "*~1*"

Resources:
  ApiResource:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - post
          - options
        AllowOrigins:
          - http://localhost:8080
          - https://dan-mba.github.io

  AddFacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_faces/
      Handler: app.lambda_handler
      Layers:
        - !Ref OpencvLayer
      Runtime: python3.7
      MemorySize: 128
      Events:
        AddFaces:
          Type: HttpApi
          Properties:
            Path: /faces
            Method: post
            ApiId: !Ref ApiResource
  OpencvLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-layer-opencv
      Description: OpenCV Dependencies
      ContentUri: ./opencv
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.7

Outputs:
  AddFacesApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Faces function"
    Value: !Sub "https://${ApiResource}.execute-api.${AWS::Region}.amazonaws.com/faces/"
