AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-opencv

  Sample SAM Template for aws-sam-opencv

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    BinaryMediaTypes:
      - "*~1*"

Resources:
  AddFacesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: add_faces/
      Handler: app.lambda_handler
      Layers:
        - !Ref OpencvLayer
      Runtime: python3.7
      MemorySize: 128
      Events:
        AddFaces:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /faces
            Method: post
  OpencvLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-layer-opencv
      Description: OpenCV Dependencies
      ContentUri: ./opencv
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddFacesApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Faces function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/faces/"
  AddFacesFunction:
    Description: "Add Faces Lambda Function ARN"
    Value: !GetAtt AddFacesFunction.Arn
  AddFacesFunctionIamRole:
    Description: "Implicit IAM Role created for Add Faces function"
    Value: !GetAtt AddFacesFunctionRole.Arn
